Set-Location "D:\Users\charl\software\Self-Determination Model"
$env:DECADIC_SELF_HOST = "127.0.0.1"
$env:DECADIC_SELF_PORT = "8765"
$env:DECADIC_NEURAL_PRESET = "full"
$env:DECADIC_PLASTICITY_ENABLED = "1"
$env:DECADIC_SPARSE_ENABLED = "1"
$env:DECADIC_GROWTH_ENABLED = "1"
$env:DECADIC_ENCODER_MODE = "hf"
$env:DECADIC_DEVICE = "cuda"
$env:DECADIC_EPISODIC_ASYNC = "1"
$env:DECADIC_N_ACTUATORS = "21"
$env:DECADIC_CURRICULUM_MODE = "legacy"
$env:DECADIC_SELF_MODEL_FEEDBACK = "1"
$env:DECADIC_GWT_ENABLED = "1"
$env:DECADIC_INTEGRATION_WINDOW_MS = "200"
$env:DECADIC_PREDICTIVE_AFFECT = "1"
$env:DECADIC_REPRESENTED_SELF = "1"
$env:DECADIC_MEMORY_EFFICIENT_TRAINING = "1"
$env:UV_CACHE_DIR = Join-Path "D:\Users\charl\software\Self-Determination Model" ".uv-cache"
& ".\.venv\Scripts\python.exe" -m uvicorn decadic.api.app:app --host 127.0.0.1 --port 8765
