@echo off
setlocal
set "REPO=%~dp0.."
cd /d "%REPO%"

set "DECADIC_SELF_HOST=127.0.0.1"
set "DECADIC_SELF_PORT=8765"
set "DECADIC_NEURAL_PRESET=full"
set "DECADIC_PLASTICITY_ENABLED=1"
set "DECADIC_SPARSE_ENABLED=1"
set "DECADIC_GROWTH_ENABLED=1"
set "DECADIC_ENCODER_MODE=hf"
set "DECADIC_DEVICE=cuda"
set "DECADIC_EPISODIC_ASYNC=1"
set "DECADIC_N_ACTUATORS=21"
set "DECADIC_CURRICULUM_MODE=legacy"
set "DECADIC_SELF_MODEL_FEEDBACK=1"
set "DECADIC_GWT_ENABLED=1"
set "DECADIC_INTEGRATION_WINDOW_MS=200"
set "DECADIC_PREDICTIVE_AFFECT=1"
set "DECADIC_REPRESENTED_SELF=1"
set "DECADIC_MEMORY_EFFICIENT_TRAINING=1"
set "UV_CACHE_DIR=%REPO%\.uv-cache"

".venv\Scripts\python.exe" -m uvicorn decadic.api.app:app --host 127.0.0.1 --port 8765
